### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by OccasionallyCrepuscular** [geronimo66/Pacig-Clock#3]
I noticed a bug where the zones and numbers didn't match up, tried to recalibrate it for the alarms to go off in the right zones by increasing age ,rebooting ,changing age on my Google account,changing date of birth on the Fitbit app is greyed out and was not possible.

 It took a factory reset of my Fitbit Versa 3 and uninstalling the watch face which you can only do after a factory reset for some reason the red text to remove it only appears then & works normally now. after re-installing it

![watch working](https://github.com/geronimo66/Pacig-Clock/assets/154762464/496c0afe-d0ec-447f-a340-fcb56e8d17cd)
![watch not working](https://github.com/geronimo66/Pacig-Clock/assets/154762464/fb5c645e-5587-4f31-9c74-fc2392a33d66)

**Comment by geronimo66** [comment]
Thanks for the report. In Version 2, the graphic view has a new size calculation. This should prevent such issues.
